/**
 * Render a self-contained static HTML dashboard from the committed run records.
 * No database, no build step, no external assets — a single page suitable for
 * the config repo's GitHub Pages. Pure and tested.
 */

import type {RunRecord} from './types.js';

const MAX_ROWS = 60;

function escapeHtml(text: string): string {
	return text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');
}

function severityCell(count: number, className: string): string {
	const shown = count > 0 ? String(count) : '·';
	return `<td class="sev ${className}">${shown}</td>`;
}

function row(record: RunRecord): string {
	const {bySeverity} = record.totals;
	const filed = record.filing ? String(record.filing.filed) : '—';
	return [
		'<tr>',
		`<td class="ts">${escapeHtml(record.timestamp)}</td>`,
		`<td><span class="mode ${record.mode}">${record.mode}</span></td>`,
		`<td class="num">${record.totals.repos}</td>`,
		`<td class="num">${record.totals.findings}</td>`,
		severityCell(bySeverity.critical, 'critical'),
		severityCell(bySeverity.high, 'high'),
		severityCell(bySeverity.medium, 'medium'),
		severityCell(bySeverity.low, 'low'),
		`<td class="num">${filed}</td>`,
		'</tr>',
	].join('');
}

/** Render the dashboard HTML for a set of run records (newest first). */
export function renderDashboard(records: RunRecord[]): string {
	const sorted = [...records].sort((a, b) =>
		b.timestamp.localeCompare(a.timestamp),
	);
	const latest = sorted[0];
	const rows = sorted.slice(0, MAX_ROWS).map(row).join('\n');

	const summary = latest
		? `Latest run ${escapeHtml(latest.timestamp)} — ${latest.totals.findings} finding(s) across ${latest.totals.repos} repo(s).`
		: 'No runs recorded yet.';

	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sentinel</title>
<style>
:root { color-scheme: dark; }
body { font-family: system-ui, sans-serif; background: #1a1b26; color: #a9b1d6; margin: 0; padding: 2rem; }
h1 { color: #7aa2f7; margin: 0 0 .25rem; font-size: 1.4rem; }
p.summary { color: #c0caf5; margin: 0 0 1.5rem; }
table { border-collapse: collapse; width: 100%; font-size: .9rem; }
th, td { padding: .5rem .6rem; text-align: left; border-bottom: 1px solid #292e42; }
th { color: #565f89; font-weight: 600; text-transform: uppercase; font-size: .72rem; letter-spacing: .04em; }
td.num, td.sev { text-align: right; font-variant-numeric: tabular-nums; }
.ts { color: #9aa5ce; font-variant-numeric: tabular-nums; }
.mode { padding: .1rem .45rem; border-radius: 999px; font-size: .72rem; }
.mode.live { background: #2d3b2d; color: #9ece6a; }
.mode.dry-run { background: #3b352d; color: #e0af68; }
.mode.audit-only { background: #2d3242; color: #7dcfff; }
.sev.critical { color: #f7768e; }
.sev.high { color: #ff9e64; }
.sev.medium { color: #e0af68; }
.sev.low { color: #565f89; }
footer { margin-top: 1.5rem; color: #565f89; font-size: .8rem; }
</style>
</head>
<body>
<h1>🛡️ Sentinel</h1>
<p class="summary">${summary}</p>
<table>
<thead><tr>
<th>Run</th><th>Mode</th><th>Repos</th><th>Findings</th>
<th>Crit</th><th>High</th><th>Med</th><th>Low</th><th>Filed</th>
</tr></thead>
<tbody>
${rows}
</tbody>
</table>
<footer>Generated by <a href="https://docs.nanocollective.org/sentinel/docs" style="color:#7aa2f7">Sentinel</a> from committed run records.</footer>
</body>
</html>
`;
}
